### PR TITLE
Add slower diagonal movement and deceleration

### PR DESCRIPTION
**Pull request by kenandizdarevic**
Add run by utilizing Vector2 for calculating current speed. This makes it possible for the player to accelerate up to a certain speed. When no input is detected the player will instantly stop.

Setting a higher acceleration value will make the acceleration go faster due to the multiplication with Time.deltaTime.

### CODE REVIEW

**Review by Cactooz — APPROVED** [review]
LGTM
A bit chuggy when stopping fully now but product owner approved it.

**Comment by kenandizdarevic** [comment]
Slower sideways, backward, and diagonal movement update. Using Pythagoran theorem to calculate correct diagonal speed. Add new movement parameters: slowSpeedWalk and slowSpeedRun.

Add deceleration with the use of Vector2.MoveTowards().

**Review by Cactooz — CHANGES_REQUESTED** [review]
Merge with dev first

**Review by Cactooz — APPROVED** [review]
Looks good now!

**Pull request merged**
